### ISSUE TITLE
Changing namespace format to namespace_IMAGENAME_hashvalue

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#397]
When deploying an atomicapp it's namespace is commonly used as `default`. From our use cases as well as multiple examples that have appeared, many users are encountering  the issue of "this namespace is already in use" when deploying another example without a configured answers.conf file.

@dustymabe and I encountered these issues recently when working on a multi-inherited Nuleculized application.

I propose that we change namespacing containers from:

`atomic_NAMESPCE_HASHVALUE`

to

`NAMESPACE_IMAGENAME_HASHVALUE`

In order to indicate what containers have been deployed by atomicapp.

I also propose that we change the value 'default' as a namespace to 'atomicapp' to better indicate what has been deployed.

**Comment by dustymabe** [comment]
@charliedrage To be clear we are only talking about doing this if the user didn't provide "--name" in the docker run command. We can't change that right now because of docker links. 

I like `NAMESPACE_IMAGENAME_HASHVALUE`. I don't know if I like making `atomicapp` the default namespace though. I like keeping it set as `default`, but I also like some indication that this is an atomicapp. Perhaps we can just do `atomicapp_NAMESPACE_IMAGENAME_HASHVALUE`.

**Comment by charliedrage** [comment]
@dustymabe 
only [a-zA-Z0-9][a-zA-Z0-9_.-] are only allowed in the image name.

For example, if we have centos/httpd:latest. What should we convert it as, centos-httpd-latest, centos.httpd.latest?

**Comment by dustymabe** [comment]
I would go with dashes

**Comment by dustymabe** [comment]
cdrage is this fixed now with #422?

**Comment by cdrage** [comment]
Yup. Thought that this would close automatically with the merge comment ^^ Closin'.
