### ISSUE TITLE
atomic install does not work due to name collision

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#51]
During atomic install of mongoDB-atomicapp I get the following error: http://fpaste.org/220791/31372419/ 
It seems like that the container names collide...

**Comment by aweiteka** [comment]
This should be resolved by PR #50 . Notice `-v :/atomicapp`. This is due to some (bug?) issue where ${PWD} is not resolving. Until this is merged you can workaround this by overriding the base image LABELs like this: https://github.com/aweiteka/nulecule/blob/helloworld/examples/helloapache/Dockerfile
