### ISSUE TITLE
Consider rebasing Atomic App image on a stripped-down OS

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomicapp#544]
The atomicapp example container, based on CentOS7, is 289MB in size.  That's very large for an empty container.   If we want people to actually build their apps on top of it, then it needs to be smaller ... in the neighborhood of 30 to 50MB.  

Would it be possible for us to obtain or produce a stripped-down OS for a smaller image?

**Comment by cdrage** [comment]
@jberkus 

Yeah..... it's a bit *too* big.

I actually did a PR a few months back about using alpine linux instead, reducing it to 100mb, but we decided on a consistent platform instead for Atomic App.

One of the problems is the fact that we use a lot of dependencies (for ex. we actually *install* Docker, despite using the host's docker socket since we communicate with run commands rather than the API) within the base image and wish to move to a more API approach similar to how we communicate with OpenShift via the web API and (eventually) Kubernetes as well. 

@alecbenson did some awesome work on the Go implementation of Nulecule being able to reduce the image in size to less than 10Mb. I've started a little bit of work on it, namely just the README  here https://github.com/cdrage/atomicapp-go . Eventually we want to have the image as small as possible so Nuleculized apps are more portable.

So to answer your question, not at the moment :( but once the Go implementation matures, it'll just be a binary blob running on `FROM: scratch` within a container.

**Comment by cdrage** [comment]
@jberkus 

Your wish is granted :)

```sh
▶ docker images projectatomic/dev       
REPOSITORY          TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
projectatomic/dev   latest              554be7e43496        About a minute ago   78.63 MB
```

PR: #546

**Comment by jberkus** [comment]
Whoo-hoo!

**Comment by jberkus** [comment]
Closing ...
