### ISSUE TITLE
Switching from OS-specific verisons of python packages to pip with hardcoded versions.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#675]
In order to encourage third-party libraries to be added (pykube, future openshift library), we have to wait until the python package is actually available upstream on the operating system.

I suggest we switch *back* to how we had it before with Atomic App and use pip with hard-coded versions.

We use pip currently in the `Dockerfile.debian` version of Atomic App (admittedly because Debian takes a bit longer updating packages than CentOS), but not the CentOS versions.

**Comment by cdrage** [comment]
PR is #676

**Comment by LalatenduMohanty** [comment]
@cdrage I do not think it is a good idea. If we want to have atomicapp RPM in distributions e.g. CentOS and Fedora then we should stay away from pip. Because most of the build system does not have access to internet for the build environment.  This is done to make sure all packages have their build dependency and runtime dependency in the distribution and the package does not fail because of dependency issue for the user.

Also resolving dependency through RPM i.e. distribution packaging method helps to fix security vulnerabilities easily and also makes it easy to take advantage of new features of dependent packages.

**Comment by dustymabe** [comment]
This blog post by stef walter might be pertinent to this discussion: http://stef.thewalter.net/stop-deploying-packages.html

**Comment by dustymabe** [comment]
Since https://github.com/projectatomic/atomicapp/pull/676 was closed.. closing this too.
